### ISSUE TITLE
Update Requirements.txt

### ISSUE THREAD

**Issue by Anshoo-Rajput** [CrewMates-Open-Source/EduHelp#1]
Go through the python codes in the main branch and find out which libraries are used in this project. Create requirements.txt in the GSSoC21 branch and list them out in it.

**Comment by balarka135** [comment]
hello, I can fix this issue.
Please assign me this issue

**Comment by GrayFlash** [comment]
@balarka135 get started ASAP.. It will be great if you set up local environment using venv or any configuration you want and try running the script on main branch, that will give you good idea of dependencies that you need to pip install. If you face any problems, contact us.

**Comment by balarka135** [comment]
okay, Thank you
