### ISSUE TITLE
Implement Multilingual Translation System

### ISSUE THREAD

**Issue by ainy-123** [CrewMates-Open-Source/EduHelp#100]
Want to implement the multilingual translation ,so that students with different languages be benefitted from a single lecture in any particular language.
I will be using MBart model, which will be capable of translation of 50 different languages into 50 different languages.

I want to work on this issue, Kindly assign me the same. @shankhanil007

**Comment by shankhanil007** [comment]
Go ahead! Do remember GSSoC will only consider the PRs made by today for points.
