### ISSUE TITLE
Update Starter.md to add env setup details

### ISSUE THREAD

**Issue by GrayFlash** [CrewMates-Open-Source/EduHelp#13]
### You need to clone this repo as per instruction in [Starter.md](https://github.com/CrewMates-Open-Source/EduHelp/blob/GSSoC21/Starter.md) file, and then create a venv (Virtual environment), pip install packages and then update these steps in Starter.md file. Refer [this](https://github.com/GrayFlash/carbon_footprint_estimator/blob/main/env_setup.md) if you are in doubt.

**Comment by GrayFlash** [comment]
This task was expected in issue #4 but was not completed.

**Comment by Anurag-bhatia** [comment]
@GrayFlash i would like to work, kindly assign me under gssoc 21.

**Comment by GrayFlash** [comment]
@Anurag-bhatia can you provide an update on your status? It should not be taking that long, if you facing any difficulty drop a comment here or on discord. We can even have a meet if needed.
