### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [CrewMates-Open-Source/EduHelp#15]
Hi ! I would like to create a file named contributing.md which will
Add the following -

1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
It will contain all the steps required so that even a beginner could benefit from the same . It will act as a one stop shop for open source contributions
I would like to work on this as a part of GSSOC'21

**Comment by GrayFlash** [comment]
Hi, we will be more than happy if you could set up a local development environment and try understanding the project from the codebase on the ``` main ``` branch, and then try creating an issue related to implementation or improvement in the codebase. We appreciate your eagerness to contribute and will love to help you in case you are stuck, and we feel editing README is not the best way to contribute to any project. Alteast try creating some workflow-related issues or something related to our codebase.
