### ISSUE TITLE
Add project description in Readme

### ISSUE THREAD

**Issue by Anshoo-Rajput** [CrewMates-Open-Source/EduHelp#16]
You can refer to this **readme** [https://github.com/CrewMates-Open-Source/EduHelp/blob/main/README.md](url) but **don't** simply copy it. We need some changes in the description like it's for all students, not only for differently-abled students. If you still have any queries, you can ask here or at the discord channel of EduHelp.

**Comment by Subhangini** [comment]
Would like to work on this issue as a gssoc participant

**Comment by Anshoo-Rajput** [comment]
go ahead @Subhangini

**Comment by Subhangini** [comment]
Do I have to only add Project description or make a proper attractive Readme file with help of some gif ?

**Comment by GrayFlash** [comment]
@subhangini Just add a brief description, we have a different issue #23 after this one.

**Comment by Subhangini** [comment]
ok
