### ISSUE TITLE
Website for Screenshot Taker

### ISSUE THREAD

**Issue by shankhanil007** [CrewMates-Open-Source/EduHelp#2]
Make a simple website for the screenshot taker product. There should be a home page comprising of the product description, photos of the developers and project video. For details of the product, one can refer to the README file in the main branch.

**Comment by Subhangini** [comment]
I would like to work on this issue .

**Comment by GrayFlash** [comment]
@Subhangini I am assigning you this issue, please update your status in atleast 48 hours so we know if you are stuck or have any doubt.

**Comment by Subhangini** [comment]
I will create a website using html , css and js  but can you provide a blueprint of the website like how you want your website to look like. 
>For the details of the product

which product are you talking about? Is there any deadline to submit PR for this issue?

**Comment by GrayFlash** [comment]
> I will create a website using html , css and js but can you provide a blueprint of the website like how you want your website to look like.

For this particular issue, you need to just make a simple HTML page that has a form, a navigation bar, and style it a bit with CSS such that it is aligned properly. Regarding designs and the exact layout and text we need it to be filled, we will create separate issues of varying levels so you can follow up those post completion of this issue. Currently, you are free for the basic design.

> which product are you talking about?

We will make an executable file of this project and we will share the drive link through Gmail. The website should serve the purpose of displaying what our project is about and a form collecting name and Gmail id of the person requesting the access.


Hope I am clear @Subhangini

**Comment by Subhangini** [comment]
>We will make an executable file of this project and we will share the drive link through Gmail. The website should serve the purpose of displaying what our project is about and a form collecting name and Gmail id of the person requesting the access.

Ok , So basically i have to make a basic website in which i have to display what our project is about . And can you please tell me , is there any deadline like i have to complete this issue till this day ?

**Comment by GrayFlash** [comment]
Currently, we don't want you to add any info on the about page, just implement a basic form in the home-page and a navbar with Home, About Us, Contact US options, and create a structure for the website, with lorem ipsum. Design and content will go on later. It will be a single-page application, so just a heading for these will be sufficient at the moment. 

Try completing it in 48 hours, I guess it should suffice.

**Comment by shankhanil007** [comment]
@Subhangini I am providing few more details the website should comprise of :
1. Logo of our product and a brief tagline
2. Description of the product
3. About the developer's section -  Photos of the developers and links to their social handles
4. Video demo of the product - You will find the video link in the main branch of our repo.
5. Contact Us form.

**Comment by gaulghost** [comment]
Can I also work on this issue as a participant of gssoc21?

**Comment by shankhanil007** [comment]
@Subhangini is currently working on it. Keep an eye on further web dev issues we will be posting as a follow-up to this issue.

**Comment by Subhangini** [comment]
Working on this , left with few sections of the website .Can you Please increase the deadline?

**Comment by shankhanil007** [comment]
Okay! But make sure you submit a PR at max by tomorrow.
