### ISSUE TITLE
Complete the README.md, Contribution_Guidelines.md for new participants.

### ISSUE THREAD

**Issue by GrayFlash** [CrewMates-Open-Source/EduHelp#23]
I will be adding a link to google docs after discussion with mentors and Project Admin, You have to simply refer to that doc file and add 
* ~~Details about the project, i.e., AIM and Implementation in README.md. The style of README is left for your discretion.~~ Assigned to @Subhangini 
* ~~Contributing_Guidelines.md needs to be created and add our suggestions and info from the remaining portion of the doc file there.~~ -> Assigned to @AshuKV.

I need two different PR for this issue, and I will add a level1 tag over there or level2 in case I find the work actually decent and automated.

* A potential PR can be Directing any participant towards Countributing_Guidelines.md before he creates an issue.

Few <b> important</b> guidelines for you:
* Create hyperlinks like [this](https://github.com/CrewMates-Open-Source/EduHelp) and not like this one (https://github.com/CrewMates-Open-Source/EduHelp).
*  Use proper tags where ever necessary and your creativity is appreciated but don't overdo things unless you are looking for being a web designer.
* Please preview the .md file before making a PR.

**Comment by Subhangini** [comment]
I would like to work on this

**Comment by GrayFlash** [comment]
Please refer [this](https://docs.google.com/document/d/1NgP7kcJPSz0XaIq51hJkgtHk4Pm7J58N76-_0py2DTc/edit?usp=sharing) doc file for README.md part, The Contributing Guidelines part is being worked upon.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by GrayFlash** [comment]
@AshuKV, Sure go ahead, with the contribution guidelines part. You need to make a Contibution_Guidelines.md file and add content from [this doc.](https://docs.google.com/document/d/1NgP7kcJPSz0XaIq51hJkgtHk4Pm7J58N76-_0py2DTc/edit)

**Comment by Subhangini** [comment]
Can i work on this issue

**Comment by GrayFlash** [comment]
@Subhangini you are working on a different issue on the same README file, I'll assign this one to you but make a pr for the other one first, and then move to this one.

**Comment by Subhangini** [comment]
Do i also have to work on Contributing guidelines?

**Comment by GrayFlash** [comment]
@Subhangini No you need to just work on README part. @AshuKV is working on the Guidelines part.

**Comment by VibhuRajput** [comment]
can I work on this?

**Comment by prathamesh-borse** [comment]
How can I contribute to this issue under GSSoC'21 Participant?

**Comment by GrayFlash** [comment]
@VibhuRajput @viraldevpb we don't need any more contributions for README's, kindly endow upon us your expertise and enthusiasm in writing scripts, working with algorithms, and help us make the world a better place.
