### ISSUE TITLE
Recording system audio

### ISSUE THREAD

**Issue by shankhanil007** [CrewMates-Open-Source/EduHelp#34]
Write code in python for recording system audio. You can make use of PyAudio for the same. Do search for better options if any.

**Comment by SnehaVeerakumar** [comment]
Can I be assigned to this ? 
If I am assigned, 2 days of time is required to complete the work for this issue.

@shankhanil007

**Comment by shankhanil007** [comment]
Go ahead @SnehaVeerakumar. Do list all the packages you have used in "requirements.txt" file so that others can set up your environment properly.

**Comment by SnehaVeerakumar** [comment]
@shankhanil007 Sure and thank you for assigning.

**Comment by SnehaVeerakumar** [comment]
I will make a PR by tomorrow.
