### ISSUE TITLE
Screen Recorder using OpenCV and python

### ISSUE THREAD

**Issue by shankhanil007** [CrewMates-Open-Source/EduHelp#35]
Make a screen recorder using OpenCV and python. It should have the option to record a specific area of the screen as selected by the user. After the recording is stopped the video should be saved in a "videos" folder.

See below code for reference. We encourage contributors to explore new possibilities and not just restrict themselves to our code.
https://github.com/CrewMates-Open-Source/EduHelp/blob/main/Windows_GUI/SS_Taker.py

**Comment by saidrishya** [comment]
Hi, can you assign this issue to me. Thanks.

**Comment by shankhanil007** [comment]
@saidrishya I cannot assign you 2 issues at the same time. You can go ahead with this issue.

**Comment by shankhanil007** [comment]
@saidrishya Do list all the packages you have used in "requirements.txt" file so that others can set up your environment properly.

**Comment by saidrishya** [comment]
okay. when's the deadline for this.

**Comment by shankhanil007** [comment]
Try to update us about your progress by this week's end.

**Comment by shankhanil007** [comment]
@saidrishya What's your status?

**Comment by SnehaVeerakumar** [comment]
@shankhanil007  Kindly assign me. If assigned, PR will be made within 10 mins :)

**Comment by SnehaVeerakumar** [comment]
I am sorry, just now I read user must be able to choose the area

**Comment by SnehaVeerakumar** [comment]
I would like to get assigned and take 2 days.

**Comment by SnehaVeerakumar** [comment]
@shankhanil007  View the output video and if that satisfies the project constrain, I would be happy to contribute to this issue
https://1drv.ms/v/s!AhQCqna6zNwBjip3f56Ys1-YviGe?e=dxYahj

Screen size can be altered

**Comment by ainy-123** [comment]
I am GSSoC'21 participant and I want to work on this issue. As it has the tag "open for all" ,can I make the raise the PR even without being assigned?

If not, kindly assign me this issue. @SnehaVeerakumar @shankhanil007

**Comment by shankhanil007** [comment]
Sure! Go ahead
