### ISSUE TITLE
Speech to text module

### ISSUE THREAD

**Issue by shankhanil007** [CrewMates-Open-Source/EduHelp#36]
Write code for conversion of speech to text. Search for efficient and faster ways of performing the same. For demo purposes apply your code to a video and show us the text generated.

**Comment by saidrishya** [comment]
Hi, I am a participant for GSSOC 2021, can you assign this issue to me. Thank you.

**Comment by Oviyabalamurugan** [comment]
Hi,I want to create an efficient way for converting speech to text. @shankhanil007 can you assign me this issue.  I am a GSSoC21 participant.

**Comment by Oviyabalamurugan** [comment]
![image](https://user-images.githubusercontent.com/55582676/113968651-1eb6c700-9851-11eb-9d9e-1e5bb615efaa.png)
This is the sample code i tried out.

**Comment by shankhanil007** [comment]
@Oviyabalamurugan Go ahead! Remember to submit a video demo with your PR.

**Comment by shankhanil007** [comment]
@Oviyabalamurugan Do list all the packages you have used in "requirements.txt" file so that others can set up your environment properly.

**Comment by Oviyabalamurugan** [comment]
> @Oviyabalamurugan Do list all the packages you have used in "requirements.txt" file so that others can set up your environment properly.

sure will list it.

**Comment by Oviyabalamurugan** [comment]
Created a PR with essentials. PR #44.

**Comment by ainy-123** [comment]
I am GSSoC'21 participant. I want to work on this issue. As ,it is open for all, can I work on this issue without being assigned ?
If not, will you please assign this to me? @shankhanil007

**Comment by shankhanil007** [comment]
As a GSSoC participant you need to be assigned. Go ahead!

**Comment by ainy-123** [comment]
> As a GSSoC participant you need to be assigned. Go ahead!

Thanks for assigning !!
