### ISSUE TITLE
Speech-to-Text Summarization

### ISSUE THREAD

**Issue by shankhanil007** [CrewMates-Open-Source/EduHelp#38]
Perform Speech-to-Text Summarization using suitable resources. The objective of this feature is to include an MoM feature in our application that can summarize the contents of the meeting. 

We would encourage the contributors not to focus on the accuracy of summarization at the beginning. You can try improving it over the course of time.

**Comment by M2kishore** [comment]
Is it okay to use 3rd party API like Aylien Text Analysis, meaning cloud summarization?

**Comment by Anshoo-Rajput** [comment]
@M2kishore You can use it for now but try searching on how you can implement this even when one doesn't have internet connection. For now go ahead 👍

**Comment by GrayFlash** [comment]
@M2kishore keeping a summarization using NLP will be more preferable, you can refer the ```master``` branch and see the way, I did that. Also, I believe there are lot better ways to do it than the one in the ```master``` branch, so we are surely looking forward to it.

Drawbacks of using cloud summarization will be: latency issues, and the potential cost once we wish to have any project in production, so it is fine to avoid cloud for everything.

**Comment by M2kishore** [comment]
I'll see to it and update you with my PR

**Comment by shankhanil007** [comment]
@M2kishore Do list all the packages you use in "requirements.txt" file so that others can set up your environment properly.

**Comment by M2kishore** [comment]
Shall i go with [this](https://towardsdatascience.com/report-is-too-long-to-read-use-nlp-to-create-a-summary-6f5f7801d355) aproach found in internet?
or 
The following diagram [here](https://github.com/CrewMates-Open-Source/EduHelp/blob/1efc88a4e306d909fbc32356f6397e231d7a86b9/Assets/cosine_summariser_flow.jpeg)

**Comment by shankhanil007** [comment]
Hey, you are free to implement any possible solution. We are open to new ideas. We will review your PR and suggest changes.

**Comment by ainy-123** [comment]
> Hey, you are free to implement any possible solution. We are open to new ideas. We will review your PR and suggest changes.

I want to work on this issue under GSSoC'21.
Kindly assign this to me . @shankhanil007

**Comment by shankhanil007** [comment]
Okay!
