### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [CrewMates-Open-Source/EduHelp#45]
Hi I would like to create a file contributing.md and add the following -
Difference between GIT and GITHUB
How to clone,fork repository
How to create a branch and then use git push to push to repo
Create a PR
Squash commits in a single issue into one
Updating the forked and local repo as the updations are made in the upstream

**Comment by shankhanil007** [comment]
@khareyash05 We already have a file named "Contibution_Guidelines.md". Update if you want but do not create a new file. Make a PR and I will assign the necessary labels to it accordingly.
