### ISSUE TITLE
locally convert speech-to-text

### ISSUE THREAD

**Issue by Oviyabalamurugan** [CrewMates-Open-Source/EduHelp#46]
Speech Recognition module that locally converts speech-to-text. Please do assign me for this issue, i will work on it and provide a better solution.

**Comment by Oviyabalamurugan** [comment]
I have used CMU sphinx recognizer but poor accuracy can i do the PR of that so that other people also can work on the accuracy of it? @GrayFlash @shankhanil007

**Comment by shankhanil007** [comment]
Okay go ahead

**Comment by Oviyabalamurugan** [comment]
> Okay go ahead

Have created a PR #79.
