### ISSUE TITLE
addition in Contribution_Guidelines.md

### ISSUE THREAD

**Issue by khareyash05** [CrewMates-Open-Source/EduHelp#47]
Hi I would like to add the following in Contribution_Guidelines.md
Difference between GIT and GITHUB
How to clone,fork repository
How to create a branch and then use git push to push to repo
Create a PR
Squash commits in a single issue into one
Updating the forked and local repo as the updations are made in the upstream

**Comment by GrayFlash** [comment]
@khareyash05 some of these are already there in REAAME.md files, so I don't think it will be necessary to add the same things in Guidelines. You can add these topics and links in README if you want.

**Comment by M2kishore** [comment]
I found that the default branch is not master it is GSSoC21.

**Comment by khareyash05** [comment]
@GrayFlash Created a PR, Have a look!
