### ISSUE TITLE
Invalid requirements in requirements.txt

### ISSUE THREAD

**Issue by M2kishore** [CrewMates-Open-Source/EduHelp#49]
while pip installing the requirements.txt it gives an error
>ERROR: Invalid requirement: 'Speech To Text Module requirements:' (from line 17 of requirements.txt)

>Double requirement given: pillow==6.2.0 (from -r requirements.txt (line 31)) (already in Pillow==8.1.2 (from -r requirements.txt (line 9)), name='pillow'

solution: The line should be commented out or removed.

**Comment by Anshoo-Rajput** [comment]
@M2kishore yes! You are right. Remove all the comments and topics. And sort all the packages in alphabetical order.
