### ISSUE TITLE
[Gssoc'21] Smooth Scrolling on index.html

### ISSUE THREAD

**Issue by arpit456jain** [CrewMates-Open-Source/EduHelp#52]
The scrolling on index.html is very fast I would like to make it smooth

**Comment by arpit456jain** [comment]
@shankhanil007 kindly review my PR

**Comment by arpit456jain** [comment]
@shankhanil007 I did not get any points for this please look into it and pr is also not showing in my profile

**Comment by shankhanil007** [comment]
![image](https://user-images.githubusercontent.com/58778597/115133720-ea4cc300-a027-11eb-800e-bd9069395f35.png)
Hey, the PR is closed so it will show under the closed PR section.  And the relevant tags are already added. You should receive the points.

**Comment by arpit456jain** [comment]
> ![image](https://user-images.githubusercontent.com/58778597/115133720-ea4cc300-a027-11eb-800e-bd9069395f35.png)
> Hey, the PR is closed so it will show under the closed PR section. And the relevant tags are already added. You should receive the points.

@shankhanil007 i had received the points they are updated in leaderboard but its not reflecting in my profile section
And same for my 2nd PR😅

**Comment by shankhanil007** [comment]
Great. Work on your other assigned issues. Will suggest some more changes to the website soon.
