### ISSUE TITLE
[Gssoc'21] Enhancement in index.html

### ISSUE THREAD

**Issue by arpit456jain** [CrewMates-Open-Source/EduHelp#53]
I would like to make some enhancement on index.html

**Comment by Aayush-hub** [comment]
@arpit456jain Can you share your ideas, what do you want to achieve?

**Comment by arpit456jain** [comment]
> @arpit456jain Can you share your ideas, what do you want to achieve?

The contact form is not in center and the. Text is not visible i will try make it better

Social media icons are static i will make them dynamic and add animation to them

Text is very big in mobile view i write some media queries for it.

**Comment by arpit456jain** [comment]
There is lots of work i can do on index.html

**Comment by arpit456jain** [comment]
Team section is not responsive at all

**Comment by Anshoo-Rajput** [comment]
Sure @arpit456jain. Go ahead!

**Comment by CMELAKKIA** [comment]
@D3ADSH0T25  @Aayush-hub  I would like to add dark mode to your page . I would align and add animation to meet the team section .If assigned I'll complete within 2 days.

**Comment by arpit456jain** [comment]
@CMELAKKIA please create a new issue

**Comment by arpit456jain** [comment]
@D3ADSH0T25 kindly review my PR
