### ISSUE TITLE
Enhancing index.html page

### ISSUE THREAD

**Issue by CMELAKKIA** [CrewMates-Open-Source/EduHelp#58]
I would like to add dark mode to your page . I would align and add animation to meet the team section .If assigned I'll complete within 2 days.

**Comment by arpit456jain** [comment]
@CMELAKKIA are you working on this issue ? If Yes then please keep in mind that i had already make the team section responsive and added a new contact section so don't forget to pull the latest code 

If no please let me know i would like to do this ☺️
