### ISSUE TITLE
Tech Stack Update ( LOGO add ) 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [CrewMates-Open-Source/EduHelp#6]
I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

**Comment by GrayFlash** [comment]
@rohank2502 I'll assign you this issue, but it is currently on low priority. We wish you can focus more on env setup locally and getting development started. We feel that part is tougher and might need a little more help from our side, so do that setup first, send a status update and I'll assign this issue to you as well. If you face any difficulty ask for help.

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> @rohank2502 I'll assign you this issue, but it is currently on low priority. We wish you can focus more on env setup locally and getting development started. We feel that part is tougher and might need a little more help from our side, so do that setup first, send a status update and I'll assign this issue to you as well. If you face any difficulty ask for help.

Ok I will try my best !!

**Comment by Anshoo-Rajput** [comment]
@rohank2502 What's your status?

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> @rohank2502 What's your status?

I am done with this but as this is low priority I don't create or IF you think to get this issue merged i will create or within 15 mins

**Comment by Anshoo-Rajput** [comment]
@rohank2502 Your PR will be reviewed by us and if it looks fine to us we will merge it.

**Comment by GrayFlash** [comment]
@rohank2502 we will merge it... no worries... If you have done some work make a PR, we do appreciate the efforts of each participant and we will add tag accordingly.

**Comment by VibhuRajput** [comment]
can I design a logo for this?
