### ISSUE TITLE
New and Better Contact section on a new page

### ISSUE THREAD

**Issue by arpit456jain** [CrewMates-Open-Source/EduHelp#64]
I would like to add New and Better Contact section on a new page current contact section is very dull

**Comment by shankhanil007** [comment]
I am closing this issue at the moment because we cannot assign so many issues to one person at the same time. At first complete issue #63 and remind me to reopen this issue.

**Comment by arpit456jain** [comment]
ok

**Comment by arpit456jain** [comment]
@shankhanil007 now i have a made a PR for my existing issue so you can reopen this

**Comment by arpit456jain** [comment]
@shankhanil007 kindly review my PR
