### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [CrewMates-Open-Source/EduHelp#7]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigned !!

**Comment by GrayFlash** [comment]
You can move ahead with this issue.

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> You can move ahead with this issue.

Thanks !!
