### ISSUE TITLE
changing footer color

### ISSUE THREAD

**Issue by arpit456jain** [CrewMates-Open-Source/EduHelp#71]
changing footer color

**Comment by arpit456jain** [comment]
<img width="960" alt="ss" src="https://user-images.githubusercontent.com/55352601/115233846-063e8a80-a136-11eb-9bfc-46add1db632d.png">

@shankhanil007 is it ok?

**Comment by arpit456jain** [comment]
<img width="960" alt="ss2" src="https://user-images.githubusercontent.com/55352601/115234578-d17f0300-a136-11eb-8a32-c67749994e1a.png">

or if you prefer dark color

**Comment by shankhanil007** [comment]
Dark one

**Comment by arpit456jain** [comment]
ok making a PR
