### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by arpit456jain** [CrewMates-Open-Source/EduHelp#73]
I would like to add a preloader on which edu help will be written in bold and large font and if you have any logo for your website then i can put it also there and it will disappear in 2 or 3 sec depending how much time the index.html page taking to load

**Comment by arpit456jain** [comment]
@shankhanil007 kindly Assign me this issue and review my pr for footer background colour

**Comment by arpit456jain** [comment]
@shankhanil007 can you provide me  any logo or something?

**Comment by shankhanil007** [comment]
Use any good standard preloader.

**Comment by arpit456jain** [comment]
@shankhanil007 the PR you merged for dark mode is not working properly please revert it

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/115394023-fd19f000-a1ff-11eb-9eb9-a3c9d3d67ea8.mp4

**Comment by shankhanil007** [comment]
Thanks for pointing it out. I didn't notice that on refreshing it disappears. Will revert it shortly.

**Comment by arpit456jain** [comment]
> Thanks for pointing it out. I didn't notice that on refreshing it disappears. Will revert it shortly.

No problem . And i would love to add tha dark mode to website if it is level 3 issue

**Comment by arpit456jain** [comment]
@shankhanil007 i have made 2 preloaded as sample have a look 

https://user-images.githubusercontent.com/55352601/115531171-18ddce80-a2b2-11eb-89c1-7383d2ff3ddc.mp4

**Comment by shankhanil007** [comment]
I see that the 1st pre-loader is working very slowly. Is the EduHelp logo getting hanged?
The 2nd is working smoothly though.

**Comment by arpit456jain** [comment]
no its fine may be my system was getting hanged.
take a look now

https://user-images.githubusercontent.com/55352601/115571617-cb2a8b80-a2dc-11eb-8bb9-24595f51797c.mp4

@shankhanil007

**Comment by arpit456jain** [comment]
@shankhanil007 which preloader should i add to website? 1st one or 2nd one

**Comment by shankhanil007** [comment]
Okay cool! Go ahead with the EduHelp logo one.

**Comment by arpit456jain** [comment]
@shankhanil007 kindly review my PR
