### ISSUE TITLE
Improving the Dark Mode

### ISSUE THREAD

**Issue by shankhanil007** [CrewMates-Open-Source/EduHelp#78]
Add a dark theme to the website which should persist even after refreshing the page. Any creative ideas for the dark theme are highly welcomed.

**Comment by arpit456jain** [comment]
@shankhanil007  
You just merge the PR for reverting the dark mode changes😅😅 i think there is no dark mode now

And you added the labels to the PR which your had removed because his feature is not working properly 😅

If you did this intentionally then its ok 👍

**Comment by arpit456jain** [comment]
@shankhanil007 if you allow me i want to add dark mode in website before adding preloader because it will take time.

But i had already prepared the dark mode for website just have to make a PR

**Comment by CMELAKKIA** [comment]
@shankhanil007   i would like to get assigned in this issue

**Comment by arpit456jain** [comment]
> @shankhanil007 i would like to get assigned in this issue

@CMELAKKIA you had already made a PR and got level 3 labels on it  although your feature did not worked properly technically you don't deserve the points but you got and that's ok for me you did work and got point's 

But i think
Now i should get a chance to add dark mode @shankhanil007 i had already done added this in my local system in a new branch just have to make a pr for that.

**Comment by CMELAKKIA** [comment]
@arpit456jain  Please do not comment about my points that is not your concern. You have already commented about your work now wait till the mentors respond.

**Comment by arpit456jain** [comment]
@CMELAKKIA i am not commenting on your points... 
i am commenting on your code... first you should check you code properly before opening a PR you just add some css and js and maked the pr...

In this GSSoC'21 i have seen  like many of you who are adding **in-complete dark mode**.
Because they just copy the code from internet and paste it... they don't know the concept behind this...

**Comment by arpit456jain** [comment]
> @shankhanil007 if you allow me i want to add dark mode in website before adding preloader because it will take time.
> 
> But i had already prepared the dark mode for website just have to make a PR



https://user-images.githubusercontent.com/55352601/115441014-015d0200-a22e-11eb-9c5a-8090532d138a.mp4

This is how it should work

**Comment by shankhanil007** [comment]
> @shankhanil007
> You just merge the PR for reverting the dark mode changes😅😅 i think there is no dark mode now
> 
> And you added the labels to the PR which your had removed because his feature is not working properly 😅
> 
> If you did this intentionally then its ok 👍

Yeah, I forgot to remove this issue after merging the revert dark theme PR.

**Comment by arpit456jain** [comment]
@shankhanil007 can i make the pr?

**Comment by shankhanil007** [comment]
Yes, I reassigned points to @CMELAKKIA later on for the work done by @CMELAKKIA, even if there was a bug.  I wouldn't have assigned points if I had noticed the bug in the first place before merging. Since this is an open-source project, bugs are quite common to occur and they can be rectified in subsequent issues and PRs. 

I am not concerned about what contributors are doing in other GSSoC projects. And assigning points is the job of the mentors. Please don't raise questions on other contributors' points.

**Comment by shankhanil007** [comment]
@arpit456jain Since you commented first, I am assigning you this issue.

**Comment by arpit456jain** [comment]
Thanks @shankhanil007 making the pr in 2 to 3 min

**Comment by arpit456jain** [comment]
@shankhanil007 kindly review my PR
