### ISSUE TITLE
New And Better Our Teams Section

### ISSUE THREAD

**Issue by arpit456jain** [CrewMates-Open-Source/EduHelp#81]
I would like to add a new and better "Our teams section"

**Comment by arpit456jain** [comment]
@shankhanil007 kindly Assign me this issue i have a very cool our team section for this website 
You would surely love it

**Comment by shankhanil007** [comment]
Noice!

**Comment by arpit456jain** [comment]
@shankhanil007 kindly review my PR and add same labels to it
