### ISSUE TITLE
You Tube video embedded on website

### ISSUE THREAD

**Issue by arpit456jain** [CrewMates-Open-Source/EduHelp#86]
Currently there is an image on clicking that image we redirect to YouTube , but i would like to embed that  video on home page itself . 
user can watch the video without leaving website

**Comment by arpit456jain** [comment]
@shankhanil007 kindly assign me this issue

**Comment by arpit456jain** [comment]
It is looking like this

https://user-images.githubusercontent.com/55352601/115947984-fb467a00-a4e8-11eb-8076-e178e973f946.mp4

**Comment by shankhanil007** [comment]
Don't keep the video display so wide. Keep it medium-sized, center-aligned  with spacing on the left and right sides

**Comment by arpit456jain** [comment]
ok

**Comment by arpit456jain** [comment]
@shankhanil007 kindly review my PR
