### ISSUE TITLE
Improving About us Section

### ISSUE THREAD

**Issue by arpit456jain** [CrewMates-Open-Source/EduHelp#87]
I would like to give a try for Improving About us Section

**Comment by arpit456jain** [comment]
@shankhanil007 kindly assign me this issue and review my PR

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/116228323-c2b9d100-a772-11eb-9c8b-adc7f4c6e29f.mp4

@shankhanil007  may i make a PR for this

**Comment by arpit456jain** [comment]
data , text can be edited as per your own convenience

**Comment by shankhanil007** [comment]
>  about.us.page.for.edu.help.mp4 
> @shankhanil007 may i make a PR for this

Go ahead

**Comment by arpit456jain** [comment]
@shankhanil007 kindly review my PR
