### ISSUE TITLE
Screen Recorder using OpenCV and python. 

### ISSUE THREAD

**Issue by shankhanil007** [CrewMates-Open-Source/EduHelp#9]
Make a screen recorder using OpenCV and python. It should have the option to record a specific area of the screen as selected by the user. After the recording is stopped the video should be saved in "videos" folder.

See below code for reference. We encourage contributors to explore new possibilities and not just restrict themselves to our code. 
https://github.com/CrewMates-Open-Source/EduHelp/blob/main/Windows_GUI/SS_Taker.py

**Comment by fomalhauting** [comment]
I would like to work on this, could you assign it to me?

**Comment by anandhu-eng** [comment]
hello im gssoc 21 participant and python enthusiast.
please do assign it to me:)

**Comment by GrayFlash** [comment]
It's been 4 days of inativity, so I'll assign it you as well @anandhu-eng

**Comment by anandhu-eng** [comment]
> It's been 4 days of inativity, so I'll assign it you as well @anandhu-eng

thanks!!

**Comment by VibhuRajput** [comment]
can I work on this?

**Comment by shankhanil007** [comment]
@VibhuRajput Go ahead. It's a level3 issue, so I am assigning multiple contributors.

**Comment by shankhanil007** [comment]
We will accept PRs if we find proper implementation. Finally, the best code will be chosen after discussion with all the mentors.

**Comment by shankhanil007** [comment]
Contributors working on this issue @VibhuRajput and @anandhu-eng what's your status?
