### ISSUE TITLE
Text to speech conversion.

### ISSUE THREAD

**Issue by ainy-123** [CrewMates-Open-Source/EduHelp#97]
In continuation to the speech to text summarizer, we can implement a system ,which will be able to convert the summarized text into audio .
It will be easy to get the summary of whole lecture/discussion in an audio form .

So,I want to implement a text to speech conversion system.

I want to work on this issue under GSSoC'21. 
Kindly assign me the same. @shankhanil007

**Comment by shankhanil007** [comment]
Good work!
